# Form implementation generated from reading ui file 'su_kien.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(272, 131)
        self.btnThayDoi = QtWidgets.QPushButton(parent=Form)
        self.btnThayDoi.setGeometry(QtCore.QRect(70, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnThayDoi.setFont(font)
        self.btnThayDoi.setObjectName("btnThayDoi")
        self.lblKetQua = QtWidgets.QLabel(parent=Form)
        self.lblKetQua.setGeometry(QtCore.QRect(40, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblKetQua.setFont(font)
        self.lblKetQua.setObjectName("lblKetQua")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnThayDoi.setText(_translate("Form", "Thay đổi"))
        self.lblKetQua.setText(_translate("Form", "TextLabel"))
